[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "toxichome-axiom"
version = "3.0.0"
authors = [
  { name="Toxichome", email="contact@toxichome.cc" },
]
description = "Official Python SDK for the Axiom API Gateway"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "httpx>=0.25.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://toxichome.cc"


