from typing import Any, Optional

from fastapi import HTTPException


class ErrorCodes:
    # Auth Errors
    AUTH_MISSING_HEADER = "AUTH_MISSING_HEADER"
    AUTH_INVALID_FORMAT = "AUTH_INVALID_FORMAT"
    AUTH_INVALID_KEY = "AUTH_INVALID_KEY"
    AUTH_INVALID_SECRET = "AUTH_INVALID_SECRET"
    AUTH_INSUFFICIENT_MODE = "AUTH_INSUFFICIENT_MODE"
    AUTH_SCOPE_DENIED = "AUTH_SCOPE_DENIED"

    # User Auth Errors
    AUTH_USER_EXISTS = "AUTH_USER_EXISTS"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_TOKEN_STOLEN = "AUTH_TOKEN_STOLEN"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"
    AUTH_RATE_LIMITED = "AUTH_RATE_LIMITED"
    AUTH_WEAK_PASSWORD = "AUTH_WEAK_PASSWORD"
    AUTH_MAGIC_LINK_EXPIRED = "AUTH_MAGIC_LINK_EXPIRED"
    AUTH_PROJECT_NOT_CONFIGURED = "AUTH_PROJECT_NOT_CONFIGURED"
    AUTH_OTP_INVALID = "AUTH_OTP_INVALID"

    # Database Errors
    DB_NOT_FOUND = "DB_NOT_FOUND"
    DB_TABLE_NOT_FOUND = "DB_TABLE_NOT_FOUND"
    DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED"
    DB_QUERY_FAILED = "DB_QUERY_FAILED"
    DB_QUERY_TIMEOUT = "DB_QUERY_TIMEOUT"
    DB_QUERY_BLOCKED = "DB_QUERY_BLOCKED"
    DB_QUERY_INVALID = "DB_QUERY_INVALID"
    DB_MODE_DENIED = "DB_MODE_DENIED"
    DB_FILTER_REQUIRED = "DB_FILTER_REQUIRED"

    # Storage Errors
    FS_NOT_FOUND = "FS_NOT_FOUND"
    FS_PATH_NOT_FOUND = "FS_PATH_NOT_FOUND"
    FS_PERMISSION_DENIED = "FS_PERMISSION_DENIED"
    FS_LIMIT_EXCEEDED = "FS_LIMIT_EXCEEDED"
    FS_FILE_TOO_LARGE = "FS_FILE_TOO_LARGE"
    FS_EXTENSION_BLOCKED = "FS_EXTENSION_BLOCKED"
    FS_UPLOAD_EXPIRED = "FS_UPLOAD_EXPIRED"
    FS_UPLOAD_INVALID = "FS_UPLOAD_INVALID"
    FS_CHECKSUM_MISMATCH = "FS_CHECKSUM_MISMATCH"

    # Rate Limiting
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    RATE_LIMIT_BLOCKED = "RATE_LIMIT_BLOCKED"

    # Input Validation
    INPUT_INVALID_JSON = "INPUT_INVALID_JSON"
    INPUT_SCHEMA_INVALID = "INPUT_SCHEMA_INVALID"
    INPUT_VALUE_INVALID = "INPUT_VALUE_INVALID"
    INPUT_PATH_TRAVERSAL = "INPUT_PATH_TRAVERSAL"
    INPUT_TOO_LARGE = "INPUT_TOO_LARGE"

    # Federation
    FED_SERVER_DOWN = "FED_SERVER_DOWN"
    FED_CIRCUIT_OPEN = "FED_CIRCUIT_OPEN"

    # System
    WEBHOOK_QUEUE_FULL = "WEBHOOK_QUEUE_FULL"
    SERVER_INTERNAL = "SERVER_INTERNAL"
    SERVER_UNAVAILABLE = "SERVER_UNAVAILABLE"


class AxiomException(HTTPException):
    def __init__(
        self,
        code: str,
        message: str,
        status_code: int = 400,
        details: Optional[Any] = None,
    ):
        self.code = code
        self.message = message
        self.details = details
        super().__init__(status_code=status_code, detail=message)
