[package]
name = "axiom"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Axiom unified single-binary API gateway daemon and CLI management utility"

[dependencies]
axiom-core = { workspace = true }
axiom-metadata = { workspace = true }
axiom-cache = { workspace = true }
axiom-db = { workspace = true }
axiom-api = { workspace = true }
axiom-cli = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
mimalloc = { workspace = true }
axum = { workspace = true }
socket2 = { workspace = true }
